### ISSUE TITLE
ReDoS vulnerability in svnurl.py

### ISSUE THREAD

**Issue by SCH227** [pytest-dev/py#287]
Good night!

I found that [this regex](https://github.com/pytest-dev/py/blob/master/py/_path/svnurl.py#L316) is vulnerable to Regular Expression Denial of Service.

PoC:
------
```
>>> from py._path.svnurl import InfoSvnCommand
>>> payl = "   2256      hpk        165 Nov 24 17:55 __init__.py" + " " * 5000
>>> InfoSvnCommand(payl)
```

Attack vector:
------------------
An user accessing a (possibly remote) subversion repository that provides malicious "info" data.
Or an attacker injecting 'svn ls http://...' output (less realistic).

Fix:
-----
Use a pattern with non-overlapping groups. I can help in finding a better regex and testing if needed.

**Comment by The-Compiler** [comment]
Related: #256

**Comment by bluetech** [comment]
I doubt there's anyone using this code, so I don't think it would warrant any sort of security notification that users should bother with, but if you prepare a PR for this I'll merge & release it.

**Comment by skialpine** [comment]
https://github.com/advisories/GHSA-w596-4wvx-j9j6
https://nvd.nist.gov/vuln/detail/CVE-2022-42969

**Comment by jenstroeger** [comment]
As @skialpine mentions, the advisory now triggers [pip-audit](https://github.com/pypa/pip-audit) and thus can fail CI runs (like [this one](https://github.com/jenstroeger/python-package-template/actions/runs/3277451447/jobs/5394745182)).

Is there a fix on the horizon?

**Comment by RonnyPfannschmidt** [comment]
The issue is not considered critical, im not aware of anyone working towards a fix

**Comment by The-Compiler** [comment]
Well, congratulations to whoever it is that decided that the right path of action here is getting a CVE for...

- Something that seems very questionable to be titled a "vulnerability" in the first place (if I can control an SVN repo/server, I might as well just [Slowloris](https://en.wikipedia.org/wiki/Slowloris_(computer_security)) the initial info request, I suppose... though admittedly I didn't try that.)
- For some ~18 year old code...
- ...which is only there for historical reasons and [discouraged to use](https://github.com/pytest-dev/py/blob/master/README.rst)
- ...which, to the best of our knowledge, is [not used anywhere in the wild](https://sourcegraph.com/search?q=context:global+py.path.svn+lang:python+-file:py/_path/+-file:/py%28-%5B0-9.%5D*%29%3F/testing/path/+-repo:pytest-dev/py+-file:pypy/tool/&patternType=standard) outside of some [old PyPy development scripts](https://foss.heptapod.net/search?search=py.path.svn&nav_source=navbar&project_id=76&group_id=166&search_code=true&repository_ref=branch%2Fdefault) nobody probably uses anymore (and certainly not against random SVN servers). Note the search results seem to be copies of those PyPy scripts, as far as I can tell.
- ...which, given the above, nobody is terribly interested in maintaining
- ...yet you ended up generating nothing but noise for [hundreds of thousands of pytest users](https://github.com/pytest-dev/pytest/network/dependents), which [for historical reasons](https://docs.pytest.org/en/latest/history.html) depends on pylib (since it came from the PyPy project, like pylib does). Yes, not everyone of the half a million projects there will monitor CVEs against dependencies, but at the same time, lots of people that do (in companies and such) are probably not in that list on GitHub.

Given that it will still take some time for [pytest to get fully rid of it's `py` internals](https://github.com/pytest-dev/pytest/issues/7259), and people seem to like getting CVEs for this project (which just happens to be very popular via pytest, but pretty much unused outside of pytest), but without really making an attempt to understanding the context... can we please consider:

- Either vendoring the remaining code (`py.path` I assume) in pytest, and archiving pylib...
- ...or releasing a pylib 2.0.0 which simply drops all the code that isn't used in pytest?

Sorry if I sound frustrated. But requesting a CVE without understanding the context of the project/issue you're reporting, and then generating false reports for hundreds of thousands of pytest users is doing a major disservice to both pytest/pylib maintainers and all those users.

**Comment by RonnyPfannschmidt** [comment]
I'd go as far as to label this cve report a supply chain attack


Pytest should keep dropping pylib as it does

The cve should be added as common false positive

**Comment by The-Compiler** [comment]
> I'd go as far as to label this cve report a supply chain attack

I would not, but I'd certainly add it to my "examples of behavior causing open source maintainer burnout" list, given that we're now getting the [first pytest issue](https://github.com/pytest-dev/pytest/issues/10392) about this, and it almost certainly won't be the last one.

**Comment by bluetech** [comment]
I should have known better that this was going to happen when I replied as I did...

If someone can get the notification retracted that'd be best.

But I guess since they've already put out a security notification to the entire world and their grandmother through GitHub, the path of least resistence would be to issue a release to fix this "security issue". I'll try to do it today.

**Comment by RonnyPfannschmidt** [comment]
@bluetech @The-Compiler i woudnt mind to cut a release that drops the svn wc stuff alltogether

**Comment by The-Compiler** [comment]
@RonnyPfannschmidt agreed, and perhaps a bit more even - I opened #288 with some overview on that.

**Comment by The-Compiler** [comment]
FWIW, I've also proposed adding a note to the GitHub advisory (https://github.com/github/advisory-database/pull/761) and [tweeted a PSA](https://twitter.com/pytestdotorg/status/1582680153209339905).

**Comment by The-Compiler** [comment]
GitHub have [now reacted](https://github.com/github/advisory-database/pull/761#issuecomment-1284368619) and amended [the advisory](https://github.com/advisories/GHSA-w596-4wvx-j9j6):

> The particular codepath in question is the regular expression at `py._path.svnurl.InfoSvnCommand.lspattern` and is only relevant when dealing with subversion (svn) projects. Notablely the codepath is not used in the popular pytest project.

and apparently also added that information for Dependabot alerts:

> I've also added the codepath to the advisory so that [dependabot can more intelligently target alerts](https://docs.github.com/en/code-security/dependabot/dependabot-alerts/viewing-and-updating-dependabot-alerts#about-the-detection-of-calls-to-vulnerable-functions).

**Comment by woodruffw** [comment]
`pip-audit` maintainer here. I have no say in it, but it's a shame (in my personal opinion) that this kind of low-quality finding was assigned a CVE ID without any significant cross-checking.

I've filed a CVE rejection request with MITRE, since they're the CVE CNA in this case. If they successfully reject it, getting it removed from GHSA should also be easy.

**Comment by woodruffw** [comment]
Actually, looks like I'll be able to propose a GHSA withdrawal even if the CVE itself hasn't been retracted. I'll open a PR for that in a moment.

**Comment by woodruffw** [comment]
I've filed https://github.com/github/advisory-database/pull/762 to mark the GHSA report as withdrawn.

**Comment by jenstroeger** [comment]
@The-Compiler agreeable and funny https://github.com/pytest-dev/py/issues/287#issuecomment-1283567565 😁

@woodruffw thanks for following up on the advisory! That means that `pip-audit` won’t pick up that CVE any longer, correct?

**Comment by woodruffw** [comment]
> @woodruffw thanks for following up on the advisory! That means that `pip-audit` won’t pick up that CVE any longer once https://github.com/pypa/pip-audit/issues/385 has merged, correct?

Once that's merged *and* the OSV entry is marked as withdrawn, yeah.

**Comment by The-Compiler** [comment]
Taking the freedom to quote what I wrote over at https://github.com/github/advisory-database/pull/762#issuecomment-1286776703:

> > but to my eye the advisory is in fact talking about a real redos vulnerability. I do understand the annoyance with what you call CVE spam, but if the advisory is valid then we want to include it in our data set.
> 
> In theory, when viewed in a vacuum: indeed.
> 
> However, even a [very broad search](https://cs.github.com/?scopeName=All+repos&scope=&q=path.svn+language%3APython#5) on GitHub for the affected code yields 92 results. I've looked through them all, and from what I can tell, all the matches fall into one of those categories:
> 
> * Copies of `py` using it (in `svnurl()`, which the search captures as well)
> * Copies of `pypy` (where the `py` library originates from historically), in it's [development tools directory](https://foss.heptapod.net/search?search=py.path.svn&nav_source=navbar&project_id=76&group_id=166&search_code=true&repository_ref=branch%2Fdefault). However, PyPy has [moved away from SVN](https://www.pypy.org/posts/2010/12/pypy-migrates-to-mercurial-3308736161543832134.html) in 2010, so they're probably just bitrotting. In any case, they use the repository the current file is in, or are hardcoded to run on a specific old PyPy team server (codespeak.net). If someone has control over that, they might as well just change those scripts. Even if there are certain scripts which actually run on arbitrary SVN servers, the context they are run in is unlikely to make a DoS a real problem. But given that they won't actually work anymore for their intended original purpose, the chance of anyone running them is pretty much zero.
> 
> On the other side of the coin, you have [at least half a million projects](https://github.com/pytest-dev/pytest/network/dependents) depending on pylib via pytest, which got noise in their inbox.
> 
> I believe the main point of a CVE and security advisories is to make people aware of problems which have a real (even if small) chance of affecting them. An advisory which just adds noise to what I believe will be 100.0% of the receivers is just going to hurt the whole system and community.
> 
> In this particular case, and when viewed in context, the sheer amount of noise the advisory generates vs. its real usage is so high that the word "spam" is unfortunately very fitting. I can't help but think that "oh, I get a shiny CVE in a popular project" was the only motivation behind it.

**Comment by woodruffw** [comment]
Just to make sure there's no confusion: I'm not a maintainer of this project or of `pytest`, so my opinions are not those of the maintainers. I'm the maintainer of a separate dependency scanning project, so I have an interest in dependency feeds having a high signal-to-noise ratio. After this comment, I'll step out of this thread now (since I'm not a maintainer and I only stepped in to coordinate on the `pip-audit` side).

With that being said: I disagree that it's good that a CVE was filed for this behavior. The fact that one was filed *and* published seemingly without any review represents a series of communication and authority breakdowns; the fact that the project's own maintainers have done more investigation into exploitability potential than the original reporter seems to have is an indicator of this.

As for why that matters: not everybody is a bank, with roles dedicated to reviewing a constant deluge of security reports. In the context of more limited resources, managing security fatigue is **far** more important than reporting weakness classes like ReDoS, which don't manifest as exploitable vulnerabilities in the overwhelming majority of cases. When users get tired of useless reports, they disable their security tools entirely.

**Comment by The-Compiler** [comment]
> First of all, I did fill for a CVE, but I didn't publish it. Someone else did it.

Well, clearly something went wrong in that process then. But also clearly you requested a CVE with the intention of publishing it (despite maintainers trying to give you context around the issue), which still is... questionable at the very least.

> I find illogical it was you, but the GH advisory says "Credits - @The-Compiler".

Probably due to my [contribution to it clarifying the issue text](https://github.com/github/advisory-database/pull/761).

> The other thing I can think of, is that GH made it automatically because this is described in a public issue. But I find it strange, because I already reported other security issues to MITRE and they never got published before I informed they were made public

GitHub does not control MITRE CVEs. They only control their own GitHub Security Advisories. The CVE being published (which is what triggered the GHSA!) is something between you and MITRE.

**Comment by SCH227** [comment]
Why I filled for a CVE?
- The attack scenario and PoC described.
- A very similar issue in this same library was issued a CVE in the past.
- I first reported it on the security email, and was asked to open a public issue for it (this is discouraged). I wouldn't mind helping on issuing a fix, as I did in other high profile projects, but then there was no reply for weeks. Still, I would have waited several weeks more before publishing it.

**Comment by SCH227** [comment]
About the excessive noise generated by security alerts, indeed, that's sadly true. 
Probably in the future we will be identifying vulnerable functions and if they are called in a project's code, as this awesome project [wants to implement in Go](https://news.ycombinator.com/item?id=32737886) to avoid false-positives.
In the meanwhile, this is what we have.

**Comment by The-Compiler** [comment]
Two quick amendments on download/notification numbers:

- It was pointed out to me that my "half a million" number was wrong. Dependents of pytest won't get a security notification about this, unless they also pin `py` (which, given the intended usage of `requirements.txt` files, is rather common). Something like [250-270k](https://github.com/pytest-dev/py/network/dependents) is probably a more realistic number, assuming that almost all of the `py` users have it pulled in via pytest or its plugins (which I still believe is a pretty safe assumption).
- As a result of this issue, today pytest 7.2.0 was released, which [vendors the parts of `py`](https://github.com/pytest-dev/pytest/pull/10396) it needs. With that being slowly adopted, I'm assuming the number of projects depending on `py` will be much lower soon.

**Comment by saher-alhusayan** [comment]
Hey! related to the issue closed [here](https://github.com/pytest-dev/py/issues/290), there are other packages that use `py` such as `retry` although according to [this](https://github.com/invl/retry/issues/19), it might be a mistake and `py` shouldn't be a dependency for `retry`

is this something they need to sort or are you guys able to help with?

**Comment by juanitosvq** [comment]
`tox` also has a dependency with `py`. I opened a issue in there to see if they can get rid of the dependency like you did in `pytest`.

**Comment by juanitosvq** [comment]
> Hey! related to the issue closed [here](https://github.com/pytest-dev/py/issues/290), there are other packages that use `py` such as `retry` although according to [this](https://github.com/invl/retry/issues/19), it might be a mistake and `py` shouldn't be a dependency for `retry`
> 
> is this something they need to sort or are you guys able to help with?

`tox` also has a dependency with `py`. I opened an [issue](https://github.com/tox-dev/tox/issues/2524) in their repo to see if they can get rid of the dependency like you did in `pytest`.

**Comment by hugovk** [comment]
> * As a result of this issue, today pytest 7.2.0 was released, which [vendors the parts of `py`](https://github.com/pytest-dev/pytest/pull/10396) it needs. With that being slowly adopted, I'm assuming the number of projects depending on `py` will be much lower soon.

📉 Midweek [py PyPI numbers](https://pepy.tech/project/py?versions=*) on are down from ~2M/day to ~1.4M/day:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/1324225/199669892-63d3d581-328c-4b1a-94d3-2cad785b6eb3.png">

**Comment by mfilenko** [comment]
Hey @hotenov,

Just curious where does [`51457`](https://github.com/hotenov/playlist-along/pull/265) come from?

Adding `2022-42969` (CVE ID) to my `pipenv check --ignore` didn't help, but `51457` did 😃

Asking for future references 🙈

**Comment by hotenov** [comment]
> Hey @hotenov,
> 
> Just curious where does [`51457`](https://github.com/hotenov/playlist-along/pull/265) come from?
> 
> Adding `2022-42969` (CVE ID) to my `pipenv check --ignore` didn't help, but `51457` did 😃
> 
> Asking for future references 🙈

Hello, @mfilenko I stole it from previous reference :) by  **KeNaCo**  
But you can take ID from safety report:

![image](https://user-images.githubusercontent.com/11818507/205322072-173a2809-f4f7-41ed-acee-2b327b999924.png)

**Comment by ret2libc** [comment]
Is the POC in the description actually working for anyone?

> ```
>>>> from py._path.svnurl import InfoSvnCommand
>>>> payl = "   2256      hpk        165 Nov 24 17:55 __init__.py" + " " * 5000
>>>> InfoSvnCommand(payl)
> ```

For me it executes everything in a fraction of a second.

**Comment by RonnyPfannschmidt** [comment]
It's thinkable that recent python versions have complexity enhancements

**Comment by natke** [comment]
hi there, I am getting this CVE coming up in my project, which is using pybind with cmake, Any guidance on how I should update to remove the violation warning? Do I need to contact pybind to update their version of pytest?

**Comment by RonnyPfannschmidt** [comment]
please ask those downstream, most of the team here didnt work with pybind

**Comment by RonnyPfannschmidt** [comment]
im closing this issue now - this was a incorrectly filed issue right from the start, it showing up in tool reports simply indicates low quality of said tools
